apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-load-test
data:
  load.js: |
    import http from 'k6/http';
    import {sleep} from 'k6';
    import {randomIntBetween} from 'https://jslib.k6.io/k6-utils/1.2.0/index.js';

    export const options = {
      discardResponseBodies: true,
      scenarios: {
        success: {
          executor: 'constant-vus',
          exec: 'success',
          vus: 50,
          duration: '15m',
        },
        failure: {
          executor: 'constant-vus',
          exec: 'error',
          vus: 10,
          duration: '15m',
        },
        status: {
          executor: 'constant-vus',
          exec: 'status',
          vus: 50,
          duration: '15m',
        },
        differentPath: {
          executor: 'constant-vus',
          exec: 'differentPath',
          vus: 100,
          duration: '15m',
        },
        differentMethod: {
          executor: 'constant-vus',
          exec: 'differentMethod',
          vus: 100,
          duration: '15m',
        },
        breakingSlo: {
          executor: 'per-vu-iterations',
          exec: 'breakingSlo',
          vus: 50,
          iterations: 100,
          maxDuration: '5m',
        }
      }
    };

    function sendStatus(status) {
      http.get('http://gateway_url/listen_path/status/' + status);
    }

    export function success() {
      sendStatus(200);
    }

    export function breakingSlo() {
      sendStatus(502);
    }

    export function status() {
      switch (randomIntBetween(1, 20)) {
        case 1:
          sendStatus(500); break;
        case 2: case 3:
          sendStatus(404); break;
        default:
          sendStatus(200);
      }
    }

    export function error() {
      switch (randomIntBetween(1, 5)) {
        case 1:
          sendStatus(400); break;
        case 2:
          sendStatus(404); break;
        case 3:
          sendStatus(500); break;
        case 4:
          sendStatus(502); break;
        case 5:
          sendStatus(503); break;
      }
      sleep(randomIntBetween(1, 5)); // sleep between 1 and 5 seconds.
    }

    export function differentPath() {
      switch (randomIntBetween(1, 5)) {
        case 1:
          http.get('http://gateway_url/listen_path/cache'); break;
        case 2:
          http.get('http://gateway_url/listen_path/ip'); break;
        case 3:
          http.get('http://gateway_url/listen_path/headers'); break;
        case 4:
          http.get('http://gateway_url/listen_path/user-agent'); break;
        default:
          http.get('http://gateway_url/listen_path/image'); break;
      }

      if (randomIntBetween(1, 7) === 1) {
        sendStatus(500);
        sleep(1); // sleep between 1
      }
    }

    export function differentMethod() {
      var payload;
      var params;

      payload = JSON.stringify({
        content: 'Hello Tyk',
      });

      params = {
        headers: {
          'Content-Type': 'application/json',
        }
      };

      switch (randomIntBetween(1, 5)) {
        case 1:
          http.post("http://gateway_url/listen_path/post", payload, params);
          break;
        case 2:
          http.patch("http://gateway_url/listen_path/patch", payload, params);
          break;
        case 3:
          http.del("http://gateway_url/listen_path/delete", payload, params);
          break;
        case 4:
          http.put("http://gateway_url/listen_path/put", payload, params);
          break;
        case 5:
          http.post("http://gateway_url/listen_path/response-headers", payload, params);
          break;
      }
    }
