apiVersion: v1
kind: ConfigMap
metadata:
  name: stream
  namespace: replace_namespace
data:
  stream.json: |-
    {
      "components": {},
      "info": {
        "title": "Stream",
        "version": "1.0.0"
      },
      "openapi": "3.0.3",
      "paths": {},
      "x-tyk-api-gateway": {
        "info": {
          "name": "Streaming API Kubernetes",
          "state": {
            "active": true
          }
        },
        "server": {
          "listenPath": {
            "strip": true,
            "value": "/streams/"
          }
        },
        "upstream": {
          "url": "https://petstore.swagger.io/v2"
        }
      },
      "x-tyk-streaming": {
        "streams": {
          "example-publisher": {
            "input": {
              "http_server": {
                "path": "/pub",
                "allowed_verbs": ["POST"],
                "timeout": "1s"
              }
            },
            "output": {
              "http_server": {
                "ws_path": "/ws"
              }
            }
          }
        }
      }
    }
---
apiVersion: tyk.tyk.io/v1alpha1
kind: TykOasApiDefinition
metadata:
  name: stream
  namespace: replace_namespace
spec:
  tykOAS:
    configmapRef:
      name: stream
      namespace: replace_namespace
      keyName: stream.json
