---
apiVersion: v1
kind: ConfigMap
metadata:
  name: http-to-kafka
  namespace: replace_namespace
data:
  http-to-kafka.json: |-
    {
      "openapi": "3.0.3",
      "info": {
        "title": "http-to-kafka",
        "version": "1.0.0"
      },
      "security": [],
      "paths": {},
      "components": {
        "securitySchemes": {}
      },
      "x-tyk-streaming": {
        "streams": {
          "consumer": {
            "input": {
              "kafka": {
                "addresses": [
                  "replace_svc_name.replace_namespace.svc:replace_svc_port"
                ],
                "consumer_group": "test",
                "client_id": "tyk",
                "topics": [
                  "test"
                ]
              }
            },
            "output": {
              "http_server": {
                "stream_path": "/consume"
              }
            }
          },
          "producer": {
            "input": {
              "http_server": {
                "path": "/produce"
              }
            },
            "output": {
              "kafka": {
                "addresses": [
                  "replace_svc_name.replace_namespace.svc:replace_svc_port"
                ],
                "topic": "test"
              }
            }
          }
        }
      },
      "x-tyk-api-gateway": {
        "info": {
          "name": "http-to-kafka",
          "state": {
            "active": true
          }
        },
        "middleware": {
          "global": {
            "trafficLogs": {
              "enabled": true
            }
          }
        },
        "server": {
          "detailedActivityLogs": {
            "enabled": true
          },
          "detailedTracing": {
            "enabled": true
          },
          "listenPath": {
            "strip": true,
            "value": "/http-to-kafka/"
          }
        },
        "upstream": {
          "url": "http://httpbin.org/"
        }
      }
    }
---
apiVersion: tyk.tyk.io/v1alpha1
kind: TykStreamsApiDefinition
metadata:
  name: http-to-kafka
  namespace: replace_namespace
spec:
  tykStreams:
    configmapRef:
      name: http-to-kafka
      namespace: replace_namespace
      keyName: http-to-kafka.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: avro-to-json
  namespace: replace_namespace
data:
  avro-to-json.json: |-
    {
      "openapi": "3.0.3",
      "info": {
        "title": "avro-to-json",
        "version": "1.0.0"
      },
      "security": [],
      "paths": {},
      "components": {
        "securitySchemes": {}
      },
      "x-tyk-streaming": {
        "streams": {
          "consumer": {
            "input": {
              "kafka": {
                "addresses": [
                  "replace_svc_name.replace_namespace.svc:replace_svc_port"
                ],
                "consumer_group": "test",
                "client_id": "tyk",
                "topics": [
                  "avro"
                ]
              }
            },
            "processors": {
              "avro": {
                "operator": "to_json",
                "schema": "{ \"type\": \"record\", \"name\": \"Notification\", \"fields\": [ { \"name\": \"notificationType\", \"type\": \"enum\", \"symbols\": [\"LIKE\",\"SHARE\",\"COMMENT\"] }, { \"name\": \"msg\",  \"type\": \"string\" } ] }"
              }
            },
            "output": {
              "http_server": {
                "stream_path": "/consume"
              }
            }
          }
        }
      },
      "x-tyk-api-gateway": {
        "info": {
          "name": "avro-to-json",
          "state": {
            "active": true
          }
        },
        "middleware": {
          "global": {
            "trafficLogs": {
              "enabled": true
            }
          }
        },
        "server": {
          "detailedActivityLogs": {
            "enabled": true
          },
          "detailedTracing": {
            "enabled": true
          },
          "listenPath": {
            "strip": true,
            "value": "/avro-to-json/"
          }
        },
        "upstream": {
          "url": "http://httpbin.org/"
        }
      }
    }
---
apiVersion: tyk.tyk.io/v1alpha1
kind: TykStreamsApiDefinition
metadata:
  name: avro-to-json
  namespace: replace_namespace
spec:
  tykStreams:
    configmapRef:
      name: avro-to-json
      namespace: replace_namespace
      keyName: avro-to-json.json
