---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pump-svc-replace_release_name
  name: pump-svc-replace_release_name
spec:
  ports:
    - name: http
      port: replace_pump_port
      protocol: TCP
      targetPort: replace_pump_port
  selector:
    app: pump-replace_release_name
  type: NodePort
