apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: replace_test_name
spec:
  parallelism: 4
  separate: false
  quiet: "false"
  script:
    configMap:
      name: slo-traffic
      file: load.js
  starter:
    securityContext:
      runAsUser: replace_run_as_user
      fsGroup: replace_fs_group
  runner:
    securityContext:
      runAsUser: replace_run_as_user
      fsGroup: replace_fs_group
