apiVersion: v1
kind: Service
metadata:
  name: datadog-agent-health-svc
spec:
  ports:
    - name: datadog-agent-health
      port: replace_health_port
      protocol: TCP
      targetPort: replace_health_port
  selector:
    app: datadog
