---
apiVersion: v1
kind: Service
metadata:
  name: users-subgraph-svc
  labels:
    app: users-subgraph
spec:
  ports:
    - name: http
      port: 4201
      targetPort: 4201
  selector:
    app: users-subgraph
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-subgraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-subgraph
  template:
    metadata:
      labels:
        app: users-subgraph
    spec:
      containers:
        - image: zalbiraw/go-api-test-service:v3.0
          imagePullPolicy: IfNotPresent
          name: users-subgraph
          command:
            - ./services/graphql-subgraphs/users/server
          ports:
            - containerPort: 4201
          env:
            - name: PORT
              value: "4201"
