apiVersion: v1
kind: ConfigMap
metadata:
  name: httpbin-keyless-oas
  namespace: replace_namespace
data:
  httpbin-keyless-oas.json: |-
    {
      "info": {
        "title": "httpbin-keyless",
        "version": "1.0.0"
      },
      "openapi": "3.0.3",
      "components": {},
      "paths": {},
      "x-tyk-api-gateway": {
        "info": {
          "name": "httpbin-keyless",
          "state": {
            "active": true
          }
        },
        "server": {
          "listenPath": {
            "strip": true,
            "value": "/httpbin-keyless/"
          }
        },
        "upstream": {
          "url": "http://replace_service_url"
        }
      }
    }
---
apiVersion: tyk.tyk.io/v1alpha1
kind: TykOasApiDefinition
metadata:
  name: httpbin-keyless
  namespace: replace_namespace
spec:
  tykOAS:
    configmapRef:
      name: httpbin-keyless-oas
      namespace: replace_namespace
      keyName: httpbin-keyless-oas.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpbin-oas
  namespace: replace_namespace
data:
  httpbin-oas.json: |-
    {
      "info": {
        "title": "httpbin",
        "version": "1.0.0"
      },
      "openapi": "3.0.3",
      "security": [
        {
          "authToken": []
        }
      ],
      "paths": {},
      "components": {
        "securitySchemes": {
          "authToken": {
            "type": "apiKey",
            "in": "header",
            "name": "Authorization"
          }
        }
      },
      "x-tyk-api-gateway": {
        "info": {
          "name": "httpbin",
          "state": {
            "active": true
          }
        },
        "server": {
          "authentication": {
            "enabled": true,
            "securitySchemes": {
              "authToken": {
                "enabled": true
              }
            }
          },
          "listenPath": {
            "strip": true,
            "value": "/httpbin/"
          }
        },
        "upstream": {
          "url": "http://replace_service_url"
        }
      }
    }
---
apiVersion: tyk.tyk.io/v1alpha1
kind: TykOasApiDefinition
metadata:
  name: httpbin
  namespace: replace_namespace
spec:
  tykOAS:
    configmapRef:
      name: httpbin-oas
      namespace: replace_namespace
      keyName: httpbin-oas.json

---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: httpbin-red-product
spec:
  name: Product Red
  state: active
  active: true
  partitions:
    acl: true
  access_rights_array:
    - name: httpbin
      namespace: replace_namespace
      versions:
        - Default
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: httpbin-blue-product
spec:
  name: Product Blue
  state: active
  active: true
  partitions:
    acl: true
  access_rights_array:
    - name: httpbin
      namespace: replace_namespace
      versions:
        - Default
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: httpbin-green-product
spec:
  name: Product Green
  state: active
  active: true
  partitions:
    acl: true
  access_rights_array:
    - name: httpbin
      namespace: replace_namespace
      versions:
        - Default
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: httpbin-plan-gold
spec:
  name: Gold Plan
  state: active
  active: true
  partitions:
    quota: true
    rate_limit: true
  rate: 10000
  access_rights_array:
    - name: httpbin
      namespace: replace_namespace
      versions:
        - Default
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: httpbin-plan-silver
spec:
  name: Silver Plan
  state: active
  active: true
  rate: 1000
  partitions:
    quota: true
    rate_limit: true
  access_rights_array:
    - name: httpbin
      namespace: replace_namespace
      versions:
        - Default
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: httpbin-plan-bronze
spec:
  name: Bronze Plan
  state: active
  active: true
  rate: 60
  partitions:
    quota: true
    rate_limit: true
  access_rights_array:
    - name: httpbin
      namespace: replace_namespace
      versions:
        - Default
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: httpbin-plan-basic
spec:
  name: Basic Plan
  state: active
  active: true
  rate: 3
  partitions:
    quota: true
    rate_limit: true
  access_rights_array:
    - name: httpbin
      namespace: replace_namespace
      versions:
        - Default
