---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: http-template
  labels:
    template: "true"
spec:
  name: http-template
  protocol: http
  active: true
  use_keyless: true
  proxy:
    target_url: http://example.com
    strip_listen_path: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-ingress
  annotations:
    kubernetes.io/ingress.class: tyk
    tyk.io/template: http-template
spec:
  rules:
    - http:
        paths:
          - path: /httpbin/
            pathType: Prefix
            backend:
              service:
                name: httpbin-svc
                port:
                  number: 8000
