apiVersion: v1
kind: Service
metadata:
  name: tyk-jaeger
  namespace: replace_namespace
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: tyk-tempo
    app.kubernetes.io/name: tempo
  ports:
    - name: tempo-query-jaeger-ui
      port: 16686
      protocol: TCP
      targetPort: 16686
