---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pump-svc-release_name
  name: pump-svc-release_name
spec:
  ports:
    - name: http
      port: prom_pump_port
      protocol: TCP
      targetPort: prom_pump_port
  selector:
    app: pump-release_name
  type: NodePort
