---
apiVersion: tyk.tyk.io/v1alpha1
kind: SubGraph
metadata:
  name: posts-subgraph
spec:
  schema: |
    directive @extends on OBJECT | INTERFACE

    directive @external on FIELD_DEFINITION

    directive @key(fields: _FieldSet!) on OBJECT | INTERFACE

    directive @provides(fields: _FieldSet!) on FIELD_DEFINITION

    directive @requires(fields: _FieldSet!) on FIELD_DEFINITION

    scalar _Any

    union _Entity = User

    scalar _FieldSet

    type _Service {
      sdl: String
    }

    type Entity {
      findPostByID(id: ID!): Post!
      findUserByID(id: ID!): User!
    }

    type Query {
      post(id: ID!): Post!
      posts: [Post!]!
      _entities(representations: [_Any!]!): [_Entity]!
      _service: _Service!
    }

    type User {
      id: ID!
      posts: [Post!]!
    }

    type Post {
      id: ID!
      userId: ID!
      title: String!
      body: String!
    }
  sdl: |
    extend type Query {
        post(id: ID!): Post!
        posts: [Post!]!
    }

    extend type User @key(fields: "id") {
        id: ID! @external
        posts: [Post!]!
    }

    type Post @key(fields: "id") {
        id: ID!
        userId: ID!
        title: String!
        body: String!
    }
---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: posts-subgraph
spec:
  name: posts-subgraph
  protocol: http
  active: true
  internal: true
  use_keyless: true
  graphql:
    enabled: true
    execution_mode: subgraph
    graph_ref: posts-subgraph
    version: "2"
    playground:
      enabled: false
      path: ""
  proxy:
    target_url: http://service_url/query
    listen_path: /posts-subgraph/
    disable_strip_slash: true
    strip_listen_path: true
