name: AKS Tyk Tests

# Controls when the workflow will run
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: azure

jobs:
  aks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AKS credentials
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.8.2"

      - name: Install helm
        uses: Azure/setup-helm@v4

      - name: Install newman
        run: |
          sudo apt update && \
          sudo apt install nodejs npm -y && \
          npm install -g newman

      - name: Copy .env file
        run: cp .env.example .env

      - name: Deploy tyk-cp
        run: |
          LICENSE="${{ secrets.DASH_LICENSE }}" \
          MDCB_LICENSE="${{ secrets.MDCB_LICENSE }}" \
          CLUSTER_LOCATION="${{ vars.AZURE_CLUSTER_LOCATION }}" \
          CLUSTER_MACHINE_TYPE="${{ vars.AZURE_CLUSTER_MACHINE_TYPE }}" \
          CLUSTER_NODE_COUNT="${{ vars.CLUSTER_NODE_COUNT }}" \
          ./up.sh -v -c azure tyk-cp

      - name: Sleep 1 minute
        run: sleep 60

      - name: Test Tyk deployment
        run: newman run --folder gateway --env-var "deployment=tyk-cp" tyk-k8s-demo.postman_collection.json

      - name: Destroy tyk-cp
        run: |
          CLUSTER_LOCATION="${{ vars.AZURE_CLUSTER_LOCATION }}" \
          CLUSTER_MACHINE_TYPE="${{ vars.AZURE_CLUSTER_MACHINE_TYPE }}" \
          CLUSTER_NODE_COUNT="${{ vars.CLUSTER_NODE_COUNT }}" \
          ./down.sh -v -c azure tyk-cp
