name: Tyk Redis Tests

# Controls when the workflow will run
on: [pull_request, workflow_dispatch]

jobs:
  tyk-redis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        redis:
          - redis
          - redis-cluster
          - redis-sentinel
      max-parallel: 3
    steps:
      - uses: actions/checkout@v2

      - name: Create Kind Cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
          config: .github/kind-cluster-v1.23.13.yml

      - name: Install helm
        uses: Azure/setup-helm@v1.1
        with:
          version: v3.5.3

      - name: Install newman
        run: |
          sudo apt update && \
          sudo apt install nodejs npm -y && \
          npm install -g newman

      - name: Copy .env file
        run: cp .env.example .env

      - name: Deploy tyk-cp with ${{ matrix.redis }}
        run: |
          LICENSE="${{ secrets.DASH_LICENSE }}" \
          MDCB_LICENSE="${{ secrets.MDCB_LICENSE }}" \
          ./up.sh -v \
            --namespace tyk-cp-${{ matrix.redis }} \
            --redis ${{ matrix.redis }} \
            tyk-cp

      - name: Test Tyk deployment
        run: newman run --folder gateway --env-var "deployment=control-plane" tyk-k8s-demo.postman_collection.json
