name: Tyk OSS Tests

# Controls when the workflow will run
on: [pull_request, workflow_dispatch]

jobs:
  tyk-oss:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        deployment:
          #          - datadog
          #          - elasticsearch
          #          - elasticsearch-kibana
          - k6
          - k6-slo-traffic
          - operator
          - operator-httpbin
          - operator-graphql
          - operator-udg
          - operator-federation
          - prometheus
          - prometheus-grafana
      max-parallel: 3
    steps:
      - uses: actions/checkout@v2

      - name: Create Kind Cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
          config: .github/kind-cluster-v1.23.13.yml

      - name: Install helm
        uses: Azure/setup-helm@v1.1
        with:
          version: v3.5.3

      - name: Install newman
        run: |
          sudo apt update && \
          sudo apt install nodejs npm -y && \
          npm install -g newman

      - name: Copy .env file
        run: cp .env.example .env

      - name: Deploy tyk-gateway-${{ matrix.deployment }}
        run: |
          ./up.sh -v \
            --namespace tyk-gateway-${{ matrix.deployment }} \
            --deployment ${{ matrix.deployment }}
            tyk-gateway

      - name: Test Tyk deployment
        run: newman run --folder gateway tyk-k8s-demo.postman_collection.json

      - name: Test ${{ matrix.deployment }}
        run: newman run --folder ${{ matrix.deployment }} tyk-k8s-demo.postman_collection.json
