apiVersion: batch/v1
kind: Job
metadata:
  name: create-sso-profile
spec:
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl:latest
          command:
            - "curl"
            - "-vvv"
            - "replace_dashboard_url/api/tib/profiles/"
            - '-HAuthorization: replace_auth'
            - '-HContent-Type: application/json'
            - '-d{ "ActionType": "GenerateOrLoginUserProfile","ID": "keycloak","OrgID": "replace_org_id","IdentityHandlerConfig": {"DashboardCredential": "replace_auth"},"ProviderConfig": {"CallbackBaseURL": "http://localhost:3000","FailureRedirect": "http://localhost:3000/?fail=true","UseProviders": [{"Key": "tyk-sso","Secret": "SLYnJetvXaGWkWlw4JwLboL6MGyUYB3A","DiscoverURL": "replace_well_known_endpoint","Name": "openid-connect"}]},"ProviderName": "SocialProvider","ReturnURL": "http://localhost:3000/tap","Type": "redirect","DefaultUserGroupID": "","CustomUserGroupField": "","UserGroupMapping": {}}'
      restartPolicy: Never
